language: python

python: 
  - "3.6"

services: 
  - docker

install:
  - docker build -t harshdevl/wisher:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
